_target_: topobench.loss.TBLoss

dataset_loss:
  _target_: topobench.loss.dataset.GraphMAELoss
  loss_type: sig  # Options: sce, mse, mae, sig
  alpha: 3  # Alpha parameter for SCE loss

modules_losses:
  feature_encoder: ${oc.select:model.feature_encoder.loss,null}
  backbone: ${oc.select:model.backbone.loss,null}
  readout: ${oc.select:model.readout.loss,null}