#!/usr/bin/env bash
# Auto-generated: best val per (model, dataset[, HOPSE-M F/PE branch]) — run sequentially.
# Pair script: best_val_reruns_parallel.sh (GPUs in parallel, then wait).

# simplicial/hopse_g  |  graph/BBB_Martins  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=graph/BBB_Martins transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__BBB_Martins__ds0

# simplicial/hopse_g  |  graph/BBB_Martins  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=graph/BBB_Martins transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__BBB_Martins__ds3

# simplicial/hopse_g  |  graph/BBB_Martins  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=graph/BBB_Martins transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__BBB_Martins__ds5

# simplicial/hopse_g  |  graph/BBB_Martins  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=graph/BBB_Martins transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__BBB_Martins__ds7

# simplicial/hopse_g  |  graph/BBB_Martins  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=graph/BBB_Martins transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__BBB_Martins__ds9

# simplicial/hopse_g  |  graph/CYP3A4_Veith  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=graph/CYP3A4_Veith transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__CYP3A4_Veith__ds0

# simplicial/hopse_g  |  graph/CYP3A4_Veith  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=graph/CYP3A4_Veith transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__CYP3A4_Veith__ds3

# simplicial/hopse_g  |  graph/CYP3A4_Veith  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=graph/CYP3A4_Veith transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__CYP3A4_Veith__ds5

# simplicial/hopse_g  |  graph/CYP3A4_Veith  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=graph/CYP3A4_Veith transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__CYP3A4_Veith__ds7

# simplicial/hopse_g  |  graph/CYP3A4_Veith  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=graph/CYP3A4_Veith transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__CYP3A4_Veith__ds9

# simplicial/hopse_g  |  graph/Caco2_Wang  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=graph/Caco2_Wang transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Caco2_Wang__ds0

# simplicial/hopse_g  |  graph/Caco2_Wang  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=graph/Caco2_Wang transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Caco2_Wang__ds3

# simplicial/hopse_g  |  graph/Caco2_Wang  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=graph/Caco2_Wang transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Caco2_Wang__ds5

# simplicial/hopse_g  |  graph/Caco2_Wang  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=graph/Caco2_Wang transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Caco2_Wang__ds7

# simplicial/hopse_g  |  graph/Caco2_Wang  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=graph/Caco2_Wang transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Caco2_Wang__ds9

# simplicial/hopse_g  |  graph/Clearance_Hepatocyte_AZ  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=graph/Clearance_Hepatocyte_AZ transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' model.backbone.n_layers=2 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Clearance_Hepatocyte_AZ__ds0

# simplicial/hopse_g  |  graph/Clearance_Hepatocyte_AZ  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=graph/Clearance_Hepatocyte_AZ transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' model.backbone.n_layers=2 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Clearance_Hepatocyte_AZ__ds3

# simplicial/hopse_g  |  graph/Clearance_Hepatocyte_AZ  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=graph/Clearance_Hepatocyte_AZ transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' model.backbone.n_layers=2 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Clearance_Hepatocyte_AZ__ds5

# simplicial/hopse_g  |  graph/Clearance_Hepatocyte_AZ  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=graph/Clearance_Hepatocyte_AZ transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' model.backbone.n_layers=2 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Clearance_Hepatocyte_AZ__ds7

# simplicial/hopse_g  |  graph/Clearance_Hepatocyte_AZ  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=graph/Clearance_Hepatocyte_AZ transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,up_adjacency-1,2-up_adjacency-0,down_adjacency-1,down_adjacency-2,2-down_adjacency-2]' model.backbone.n_layers=2 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=mae trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__Clearance_Hepatocyte_AZ__ds9

# simplicial/hopse_g  |  graph/MUTAG  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=graph/MUTAG transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__MUTAG__ds0

# simplicial/hopse_g  |  graph/MUTAG  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=graph/MUTAG transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__MUTAG__ds3

# simplicial/hopse_g  |  graph/MUTAG  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=graph/MUTAG transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__MUTAG__ds5

# simplicial/hopse_g  |  graph/MUTAG  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=graph/MUTAG transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__MUTAG__ds7

# simplicial/hopse_g  |  graph/MUTAG  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=graph/MUTAG transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__MUTAG__ds9

# simplicial/hopse_g  |  graph/NCI1  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=graph/NCI1 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI1__ds0

# simplicial/hopse_g  |  graph/NCI1  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=graph/NCI1 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI1__ds3

# simplicial/hopse_g  |  graph/NCI1  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=graph/NCI1 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI1__ds5

# simplicial/hopse_g  |  graph/NCI1  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=graph/NCI1 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI1__ds7

# simplicial/hopse_g  |  graph/NCI1  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=graph/NCI1 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI1__ds9

# simplicial/hopse_g  |  graph/NCI109  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=graph/NCI109 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI109__ds0

# simplicial/hopse_g  |  graph/NCI109  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=graph/NCI109 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI109__ds3

# simplicial/hopse_g  |  graph/NCI109  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=graph/NCI109 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI109__ds5

# simplicial/hopse_g  |  graph/NCI109  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=graph/NCI109 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI109__ds7

# simplicial/hopse_g  |  graph/NCI109  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=graph/NCI109 transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__NCI109__ds9

# simplicial/hopse_g  |  graph/PROTEINS  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=graph/PROTEINS transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.01 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__PROTEINS__ds0

# simplicial/hopse_g  |  graph/PROTEINS  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=graph/PROTEINS transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.01 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__PROTEINS__ds3

# simplicial/hopse_g  |  graph/PROTEINS  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=graph/PROTEINS transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.01 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__PROTEINS__ds5

# simplicial/hopse_g  |  graph/PROTEINS  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=graph/PROTEINS transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.01 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__PROTEINS__ds7

# simplicial/hopse_g  |  graph/PROTEINS  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=graph/PROTEINS transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_incidence-0,up_incidence-1,2-up_incidence-0,down_incidence-1,down_incidence-2,2-down_incidence-2]' model.backbone.n_layers=4 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.01 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=accuracy trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__graph__PROTEINS__ds9

# simplicial/hopse_g  |  simplicial/mantra_betti_numbers  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_betti_numbers transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=loss trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_betti_numbers__ds0

# simplicial/hopse_g  |  simplicial/mantra_betti_numbers  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_betti_numbers transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=loss trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_betti_numbers__ds3

# simplicial/hopse_g  |  simplicial/mantra_betti_numbers  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_betti_numbers transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=loss trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_betti_numbers__ds5

# simplicial/hopse_g  |  simplicial/mantra_betti_numbers  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_betti_numbers transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=loss trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_betti_numbers__ds7

# simplicial/hopse_g  |  simplicial/mantra_betti_numbers  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_betti_numbers transforms.hopse_encoding.pretrain_model=zinc 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=4 model.feature_encoder.out_channels=128 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=128 dataset.parameters.monitor_metric=loss trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_betti_numbers__ds9

# simplicial/hopse_g  |  simplicial/mantra_name  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_name transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=2 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_name__ds0

# simplicial/hopse_g  |  simplicial/mantra_name  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_name transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=2 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_name__ds3

# simplicial/hopse_g  |  simplicial/mantra_name  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_name transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=2 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_name__ds5

# simplicial/hopse_g  |  simplicial/mantra_name  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_name transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=2 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_name__ds7

# simplicial/hopse_g  |  simplicial/mantra_name  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_name transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0]' model.backbone.n_layers=2 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.5 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_name__ds9

# simplicial/hopse_g  |  simplicial/mantra_orientation  |  data_seed=0
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_orientation transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=0 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_orientation__ds0

# simplicial/hopse_g  |  simplicial/mantra_orientation  |  data_seed=3
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_orientation transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=3 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_orientation__ds3

# simplicial/hopse_g  |  simplicial/mantra_orientation  |  data_seed=5
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_orientation transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=5 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_orientation__ds5

# simplicial/hopse_g  |  simplicial/mantra_orientation  |  data_seed=7
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_orientation transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=7 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_orientation__ds7

# simplicial/hopse_g  |  simplicial/mantra_orientation  |  data_seed=9
python -m topobench model=simplicial/hopse_g dataset=simplicial/mantra_orientation transforms.hopse_encoding.pretrain_model=molpcba 'transforms.hopse_encoding.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' transforms.hopse_encoding.max_hop=2 transforms.hopse_encoding.max_rank=2 'model.feature_encoder.selected_dimensions=[0,1,2]' 'model.preprocessing_params.neighborhoods=[up_adjacency-0,2-up_adjacency-0]' model.backbone.n_layers=1 model.feature_encoder.out_channels=256 model.feature_encoder.proj_dropout=0.25 optimizer.parameters.lr=0.001 optimizer.parameters.weight_decay=0.0001 dataset.dataloader_params.batch_size=256 dataset.parameters.monitor_metric=f1 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 delete_checkpoint_after_test=True '+combined_feature_encodings.preprocessor_device='"'"'cuda'"'"'' dataset.split_params.data_seed=9 trainer.max_epochs=500 callbacks.early_stopping.patience=10 deterministic=True +logger.wandb.entity=gbg141-hopse logger.wandb.project=best_runs_rerun +logger.wandb.name=simplicial__hopse_g__simplicial__mantra_orientation__ds9
