
loader:
  _target_: topobench.data.loaders.GraphUniverseDatasetLoader
  parameters:
    data_domain: graph
    data_type: GraphUniverse
    data_name: GraphUniverse_VGAE
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    generation_parameters:
      task: community_detection
      universe_parameters:
        K: 10
        feature_dim: 15
        center_variance: 0.2
        cluster_variance: 0.4
        edge_propensity_variance: 0.5
        seed: 42
      family_parameters:
        n_graphs: 500
        n_nodes_range: [50, 150]
        n_communities_range: [4, 6]
        homophily_range: [0.3, 0.7]
        avg_degree_range: [1.0, 3.0]
        degree_separation_range: [0.5, 1.0]
        power_law_exponent_range: [1.5, 2.5]
        seed: ${dataset.loader.parameters.generation_parameters.universe_parameters.seed}

parameters:
  num_features: ${dataset.loader.parameters.generation_parameters.universe_parameters.feature_dim}
  num_classes: 1
  task: vgae
  monitor_metric: accuracy
  task_level: node

split_params:
  learning_setting: inductive
  data_split_dir: ${dataset.loader.parameters.data_dir}/data_splits
  data_seed: 0
  split_type: random
  k: 10
  train_prop: 0.7

dataloader_params:
  batch_size: 32
  num_workers: 0
  pin_memory: False
